export const portfolioData = {
  personal: {
    name: "Harshit Saxena",
    title: "Backend Developer & Software Engineer",
    taglines: [
      "Backend Developer",
      "API Architect",
      "Database Engineer",
      // "Cloud Infrastructure Dev",
      "Open Source Contributor",
      "Problem Solver"
    ],
    bio: "I'm a passionate Backend Developer who loves building scalable, high-performance systems. I specialize in designing RESTful APIs, microservices architecture, and cloud-native applications. When I'm not coding, I'm contributing to open source or learning new technologies.",
    location: "Lucknow, Uttar Pradesh, India",
    email: "harshitsaxena9228@email.com",
    phone: "+91 8009903128",
    availability: "Available for opportunities",
    github: "https://github.com/harshitsaxena",
    linkedin: "https://linkedin.com/in/harshitsaxena",
    twitter: "https://twitter.com/harshitsaxena",
    resume: "/resume.pdf",
    avatar: "/avatar.jpg",
    yearsOfExperience: 3,
    projectsCompleted: 20,
    githubStars: 150,
    coffees: 1000,
  },

  skills: [
    {
      category: "Languages",
      icon: "💻",
      color: "#00ff88",
      items: [
        { name: "Python", level: 50 },
        { name: "JavaScript", level: 85 },
        { name: "C++", level: 60 },
        { name: "Java", level: 80 },
        { name: "C", level: 40 },
        { name: "SQL", level: 88 },
      ]
    },
    {
      category: "Frameworks & Libraries",
      icon: "⚙️",
      color: "#00d4ff",
      items: [
        { name: "Node.js / Express", level: 88 },
        { name: "FastAPI", level: 85 },
        { name: "Django / DRF", level: 80 },
        { name: "Spring Boot", level: 65 },
        { name: "GraphQL", level: 70 },
        // { name: "gRPC", level: 60 },
      ]
    },
    {
      category: "Databases",
      icon: "🗄️",
      color: "#8b5cf6",
      items: [
        { name: "PostgreSQL", level: 90 },
        { name: "MongoDB", level: 85 },
        { name: "Redis", level: 80 },
        { name: "MySQL", level: 82 },
        // { name: "Elasticsearch", level: 65 },
        // { name: "Cassandra", level: 55 },
      ]
    },
    {
      category: "DevOps & Cloud",
      icon: "☁️",
      color: "#f97316",
      items: [
        { name: "Docker", level: 85 },
        { name: "Kubernetes", level: 65 },
        { name: "AWS (EC2, S3, RDS)", level: 78 },
        { name: "CI/CD (GitHub Actions)", level: 80 },
        { name: "Linux / Bash", level: 82 },
        { name: "Nginx", level: 75 },
      ]
    },
    {
      category: "Concepts & Architecture",
      icon: "🧠",
      color: "#f472b6",
      items: [
        { name: "REST API Design", level: 92 },
        { name: "Microservices", level: 78 },
        { name: "System Design", level: 75 },
        { name: "Data Structures & Algo", level: 85 },
        { name: "Message Queues (RabbitMQ/Kafka)", level: 70 },
        { name: "OAuth2 / JWT Auth", level: 88 },
      ]
    }
  ],

  projects: [
    {
      id: 1,
      title: "DistribuCache",
      description: "A distributed caching system built from scratch with consistent hashing, LRU eviction policy, and node replication. Handles 50k+ requests/sec with sub-millisecond latency.",
      longDescription: "Built a production-ready distributed cache supporting cluster mode, automatic failover, pub/sub messaging, and Lua scripting. Includes a CLI dashboard for monitoring cache stats, memory usage, and hit/miss ratios in real-time.",
      tech: ["Go", "Redis", "Docker", "gRPC", "Prometheus"],
      github: "https://github.com/arjunsharma/distribucache",
      live: "https://distribucache.demo.com",
      image: "/projects/distribucache.png",
      featured: true,
      category: "Systems",
      stats: { stars: 48, forks: 12, issues: 3 },
    },
    {
      id: 2,
      title: "ByteAuth — Auth Microservice",
      description: "Production-grade authentication microservice with OAuth2, JWT refresh rotation, MFA/TOTP, email verification, and rate limiting. Plug-and-play for any backend.",
      longDescription: "Handles 10k+ concurrent users. Supports Google, GitHub OAuth. Implements PKCE flow, device fingerprinting, suspicious login detection, and session management. Full audit logs.",
      tech: ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "JWT"],
      github: "https://github.com/arjunsharma/byteauth",
      live: "https://byteauth.demo.com",
      image: "/projects/byteauth.png",
      featured: true,
      category: "Security",
      stats: { stars: 63, forks: 21, issues: 5 },
    },
    {
      id: 3,
      title: "NexCommerce API",
      description: "Scalable e-commerce backend with product catalog, order management, Stripe payments, inventory tracking, and Redis caching. Reduced DB load by 65% with smart caching.",
      longDescription: "Microservices architecture with separate services for products, orders, payments, notifications, and search. Event-driven using RabbitMQ. Full-text search with Elasticsearch. Admin dashboard with analytics.",
      tech: ["Node.js", "Express", "MongoDB", "Redis", "RabbitMQ", "Stripe"],
      github: "https://github.com/arjunsharma/nexcommerce",
      live: "https://nexcommerce.demo.com",
      image: "/projects/nexcommerce.png",
      featured: true,
      category: "E-commerce",
      stats: { stars: 35, forks: 8, issues: 2 },
    },
    {
      id: 4,
      title: "LogStream — Real-time Analytics",
      description: "Real-time log aggregation and analytics pipeline processing 100k events/sec. Built with Kafka, Elasticsearch, and a live WebSocket dashboard.",
      longDescription: "Collects logs from multiple services, normalizes them, detects anomalies using ML models, and visualizes in real-time. Supports custom alert rules, log retention policies, and export to S3.",
      tech: ["Python", "Kafka", "Elasticsearch", "WebSocket", "AWS S3"],
      github: "https://github.com/arjunsharma/logstream",
      live: null,
      image: "/projects/logstream.png",
      featured: false,
      category: "Data Engineering",
      stats: { stars: 27, forks: 6, issues: 1 },
    },
    {
      id: 5,
      title: "QuickLink — URL Shortener",
      description: "High-throughput URL shortener handling 100k redirects/day with custom aliases, QR code generation, click analytics, and link expiry.",
      longDescription: "Uses base62 encoding, Bloom filters to avoid DB lookups for invalid keys, and Redis for hot URL caching. Geolocation tracking, UTM parameter support, and A/B testing for marketers.",
      tech: ["Node.js", "PostgreSQL", "Redis", "Docker", "Vercel"],
      github: "https://github.com/arjunsharma/quicklink",
      live: "https://quicklink.demo.com",
      image: "/projects/quicklink.png",
      featured: false,
      category: "Utility",
      stats: { stars: 19, forks: 5, issues: 0 },
    },
    {
      id: 6,
      title: "CodeCollab — Real-time Editor",
      description: "Collaborative code editor with real-time syncing using CRDT (Conflict-free Replicated Data Types), syntax highlighting, and video chat via WebRTC.",
      longDescription: "Implements Yjs CRDT for conflict-free collaborative editing. Supports 50+ programming languages, room-based sessions, code execution sandbox, and git-like version history.",
      tech: ["Node.js", "WebSocket", "CRDT (Yjs)", "WebRTC", "Redis"],
      github: "https://github.com/arjunsharma/codecollab",
      live: "https://codecollab.demo.com",
      image: "/projects/codecollab.png",
      featured: false,
      category: "Developer Tools",
      stats: { stars: 41, forks: 15, issues: 4 },
    },
  ],

  experience: [
    {
      title: "Backend Developer Intern",
      company: "TechStartup Pvt. Ltd.",
      location: "Remote",
      duration: "Jan 2024 – Present",
      type: "Internship",
      description: [
        "Built and maintained 15+ REST APIs using Node.js and Express serving 10k+ daily users",
        "Optimized PostgreSQL queries reducing average response time from 800ms to 120ms",
        "Implemented Redis caching layer reducing database load by 60%",
        "Set up CI/CD pipeline with GitHub Actions and Docker reducing deployment time by 70%",
      ],
      tech: ["Node.js", "PostgreSQL", "Redis", "Docker", "AWS"],
    },
    {
      title: "Freelance Backend Developer",
      company: "Self-employed",
      location: "Lucknow, India",
      duration: "Jun 2023 – Dec 2023",
      type: "Freelance",
      description: [
        "Delivered 5+ client projects including e-commerce APIs and SaaS backends",
        "Built complete authentication systems with OAuth2 and JWT for 3 different clients",
        "Designed MongoDB schemas and REST APIs handling 1k+ daily transactions",
        "Maintained 100% client satisfaction with timely delivery",
      ],
      tech: ["Python", "Django", "MongoDB", "FastAPI", "Stripe"],
    },
    {
      title: "CS Student & Open Source Contributor",
      company: "AKTU / Personal Projects",
      location: "Lucknow, India",
      duration: "2021 – 2023",
      type: "Education",
      description: [
        "Pursuing Bachelor's in Computer Science with focus on distributed systems",
        "Contributed to 5+ open source projects on GitHub with 150+ total stars",
        "Won 2 hackathons building backend systems for real-world problems",
        "Ranked top 5% on LeetCode with 300+ problems solved",
      ],
      tech: ["C++", "Python", "Data Structures", "Algorithms"],
    },
  ],

  achievements: [
    { icon: "🏆", title: "Hackathon Winner", desc: "1st place at HackIndia 2023" },
    { icon: "⭐", title: "GitHub Stars", desc: "150+ stars across projects" },
    { icon: "💡", title: "LeetCode", desc: "300+ problems, top 5%" },
    { icon: "🎯", title: "Certifications", desc: "AWS Cloud Practitioner" },
  ],

  contact: {
    heading: "Let's Build Something Great",
    subheading: "Open to full-time roles, internships, freelance projects & open source collaboration.",
    email: "arjun.sharma@email.com",
    phone: "+91 98765 43210",
    location: "Lucknow, Uttar Pradesh, India",
  }
}
